//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int employee_id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public int department_id { get; set; }
        public int user_id { get; set; }
        public bool is_admin { get; set; }
        public bool is_active { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual User User { get; set; }
    }
}
